# Generated by Django 5.2.5 on 2025-09-24 13:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='rating',
        ),
        migrations.AddField(
            model_name='movie',
            name='is_family_friendly',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Documentary', 'Documentary'), ('Thriller', 'Thriller'), ('Animation', 'Animation'), ('Fantasy', 'Fantasy'), ('Mystery', 'Mystery'), ('Adventure', 'Adventure'), ('Crime', 'Crime'), ('Musical', 'Musical'), ('War', 'War'), ('Western', 'Western'), ('Biography', 'Biography'), ('Family', 'Family'), ('Sport', 'Sport'), ('History', 'History')], max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
