# Generated by Django 5.2.5 on 2025-09-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_app', '0002_remove_movie_rating_movie_is_family_friendly_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
