# Generated by Django 5.2.5 on 2025-09-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_app', '0003_remove_review_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
