# Generated by Django 5.2.5 on 2025-09-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_app', '0004_alter_review_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='is_family_friendly',
        ),
        migrations.AddField(
            model_name='movie',
            name='family_friendly',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
