# Generated by Django 5.2.5 on 2025-09-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_app', '0005_remove_movie_is_family_friendly_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='family_friendly',
        ),
        migrations.AddField(
            model_name='review',
            name='family_friendly',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
