# Generated by Django 5.2.7 on 2025-10-03 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_app', '0007_alter_movie_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
