# Generated by Django 5.2.7 on 2025-10-05 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie_app', '0010_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='owner',
        ),
    ]
